# Generated by Django 5.0.6 on 2024-07-04 07:09

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0002_contact_phone_contact_title'),
    ]

    operations = [
        migrations.CreateModel(
            name='Method',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('method_type', models.CharField(default='manual', max_length=100)),
                ('name', models.CharField(default='Manually Added', max_length=100)),
                ('description', models.TextField(default='This contact was manually added to the database.')),
            ],
        ),
        migrations.AlterField(
            model_name='contact',
            name='source',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='contact',
            name='method',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='common.method'),
        ),
    ]
