# Generated by Django 5.0.6 on 2024-07-04 10:56

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0004_alter_contact_birthday'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='contact',
            name='last_sent',
        ),
        migrations.AddField(
            model_name='contact',
            name='recently_bounced',
            field=models.BooleanField(default=False, help_text='Whether the contact recently bounced in one of the campiagns or not.'),
        ),
        migrations.AddField(
            model_name='contact',
            name='recently_contacted',
            field=models.BooleanField(default=False, help_text='Whether the contact was recently contacted in a campaign or not.'),
        ),
        migrations.AlterField(
            model_name='contact',
            name='address',
            field=models.CharField(blank=True, help_text='The address of the contact.', max_length=255),
        ),
        migrations.AlterField(
            model_name='contact',
            name='birthday',
            field=models.DateField(blank=True, help_text='The birthday of the contact.', null=True),
        ),
        migrations.AlterField(
            model_name='contact',
            name='company',
            field=models.CharField(blank=True, help_text='The company of the contact.', max_length=100),
        ),
        migrations.AlterField(
            model_name='contact',
            name='email',
            field=models.EmailField(help_text='The email address of the contact.', max_length=254, unique=True),
        ),
        migrations.AlterField(
            model_name='contact',
            name='first_name',
            field=models.CharField(blank=True, help_text='The first name of the contact.', max_length=100),
        ),
        migrations.AlterField(
            model_name='contact',
            name='last_name',
            field=models.CharField(blank=True, help_text='The last name of the contact.', max_length=100),
        ),
        migrations.AlterField(
            model_name='contact',
            name='method',
            field=models.ForeignKey(help_text='The method used to add the contact.', null=True, on_delete=django.db.models.deletion.CASCADE, to='common.method'),
        ),
        migrations.AlterField(
            model_name='contact',
            name='phone',
            field=models.CharField(blank=True, help_text='The phone number of the contact.', max_length=20),
        ),
        migrations.AlterField(
            model_name='contact',
            name='source',
            field=models.CharField(blank=True, help_text='The source of the contact.', max_length=255),
        ),
        migrations.AlterField(
            model_name='contact',
            name='subscribed',
            field=models.BooleanField(default=True, help_text='Whether the contact is subscribed or not.'),
        ),
        migrations.AlterField(
            model_name='contact',
            name='tags',
            field=models.CharField(blank=True, help_text='Any tags you want for this contact seperated by commas.', max_length=255),
        ),
        migrations.AlterField(
            model_name='contact',
            name='title',
            field=models.CharField(blank=True, help_text='The title of the contact.', max_length=5),
        ),
    ]
